### PR TITLE
Updated Mac OS bundle

### PR DESCRIPTION
**Pull request by sbzappa**
- Added script `build_thirdparty.sh` to clone and build third party libraries to be compatible with PopTracker bundle.
- Updated `bundle_macosx_app.sh` to adjust paths for new libraries.

### CODE REVIEW

**Comment by black-sliver** [comment]
since you do ` if [ ! -d $LIB_PNG_DEST_DIR ]; then`, shouldn't `make clean` remove that at some point, so we can update dependencies? I think currently it only removes the files created by the Makefile itself (and there is one missing, i will fix later).
Also maybe `else git pull`?

**Comment by sbzappa** [comment]
> since you do ` if [ ! -d $LIB_PNG_DEST_DIR ]; then`, shouldn't `make clean` remove that at some point, so we can update dependencies? I think currently it only removes the files created by the Makefile itself (and there is one missing, i will fix later). Also maybe `else git pull`?

I could call `build_thirdparty.sh --clear-build-dir --clear-lib-dir` during make clean.

Otherwise, I don't think it's necessary to `git pull` since we're checkouting a tag branch for each repository to prevent third party potentially breaking the build at some point.

**Comment by black-sliver** [comment]
Yeah. the make clean change should suffice for now. Do you want to add that?

> Otherwise, I don't think it's necessary to git pull since we're checkouting a tag branch for each repository to prevent third party potentially breaking the build at some point.
Once we target a new tag, we have to add a way to update it. If we remember then (sure... :D), it's fine as is.

**Comment by sbzappa** [comment]
@black-sliver 
Added function to clear third party directories in `make clean` and also added a `git pull` before doing a `git checkout` on the repository.

Also, the way Freetype is setup forces me to call `autogen.sh` to generate a valid configure script. This requires `automake`, `libtool` and `autoconf`. These can be installed using brew and should be part of development setups.

**Pull request merged**
