### PR TITLE
Mention Nix package in readme

### PR DESCRIPTION
**Pull request by freyacodes**
I took the time to add this project as a package in nixpkgs, so I figured that some people would benefit from having it mentioned here.

We are currently one update behind on nixpkgs-unstable. I will see if I can find the time to update this at some point.

### CODE REVIEW

**Comment by black-sliver** [comment]
Sorry for responding so late, last week was busy for me.

I kind of have two questions -

do we want to "fix" the asset search path on source level rather than having a patch? The AUR version has a very different implementation for that [here](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=poptracker-git#n38), for example, which seems more fragile than yours.

is it fine to leave the update notification in if there is no way for a nix user to update immediately after release? There is an ifdef [here](https://github.com/black-sliver/PopTracker/blob/ae09c13f13b4ef1d5154b24021708b808f7d1b6b/src/poptracker.cpp#L201) that could be used to remove the check, or you could override the check to fetch the nix metadata instead, i guess.

**Comment by freyacodes** [comment]
> do we want to "fix" the asset search path on source level rather than having a patch? The AUR version has a very different implementation for that [here](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=poptracker-git#n38), for example, which seems more fragile than yours.

Perhaps there is a way to define it during build time without source modification? I don't think I understand the AUR solution.

> is it fine to leave the update notification in if there is no way for a nix user to update immediately after release? There is an ifdef [here](https://github.com/black-sliver/PopTracker/blob/ae09c13f13b4ef1d5154b24021708b808f7d1b6b/src/poptracker.cpp#L201) that could be used to remove the check, or you could override the check to fetch the nix metadata instead, i guess.

Thank you for making me aware of this. Ideally we could set this to somehow check the version against the latest stable branch of Nixpkgs, however I am not aware of a good way of getting that information in a simple way. Otherwise we can just disable it, as PopTracker updates could be delayed 6 months on stable even if we keep up with updates. 

CC @pyrox0

**Comment by pyrox0** [comment]
I don't know of a good way of checking that on startup since I don't know any other package that does so, most packages within nixpkgs have update checking simply disabled afaik, so we should disable it, but we should be able to backport to stable any updates that don't have breaking changes.

Also, the AUR solution seems to be a wrapper script that `cd`s into `/usr/share/poptracker` and then executes poptracker from there, but our patch should be better since we can't install things into /usr/share in nixpkgs, so we shouldn't need to worry about the AUR's solution

**Comment by black-sliver** [comment]
> so we should disable it

I agree.

> updates could be delayed 6 months on stable

Where are the 6 months coming from?

> we should be able to backport to stable any updates that don't have breaking changes

Does this mean ideally we completely split feature and bugfix/security updates? How would I inform you about critical updates?
We are in unstable versioning, so this is hard to convey, but does this mean there is stable N-1, which could be 1.0.0 and get an update to 1.0.1 and in parallel there is unstable N, which could be 1.1.0 and get an update to 1.1.1?

> ... AUR ...

Yeah, I don't think the AUR solution is great. This was more of a "there are two things now that need to fiddle with it, maybe we should fix it".

**Comment by freyacodes** [comment]
> Where are the 6 months coming from?

Nixpkgs comes in several channels. The unstable channels are close to the very latest updates provided to nixpkgs, whereas a new set of stable channels are created in May and November. `v0.25.7` is the currently available version of PopTracker on stable nixpkgs, whereas unstable is currently up to date. Although we could backport to stable.

> Does this mean ideally we completely split feature and bugfix/security updates? How would I inform you about critical updates?
We are in unstable versioning, so this is hard to convey, but does this mean there is stable N-1, which could be 1.0.0 and get an update to 1.0.1 and in parallel there is unstable N, which could be 1.1.0 and get an update to 1.1.1?

I think it should be fine to continue your existing release flow. If you have a non-breaking release, you could state that in literal words in your release notes.

**Comment by black-sliver** [comment]
So, do we want to merge this PR as-is and look at other things separately?

**Comment by black-sliver** [comment]
I'm gonna merge this and we can think about other stuff later.

**Pull request merged**
